const ApiBaseUrl = 'http://localhost:3002/api';

export const ApiApplication = {
  AUTH: {
    CONTROLLER: ApiBaseUrl + '/auth',
    LOGIN: 'log-in',
    LOGOUT: 'log-out',
    GET_PROFILE: 'profile',
  },
  USER: {
    CONTROLLER: ApiBaseUrl + '/user',
    CREATE_MEMBER: 'member',
    CREATE_ADMIN: 'admin',
    CREATE_STAFF: 'staff',
    CREATE_SHIPPER: 'shipper',
    GET_ALL_USER: '',
    GET_ALL_SHIPPER: 'shipper',
    GET_ONE: ':id',
    UPDATE: ':id',
  },
  ADDRESS: {
    CONTROLLER: ApiBaseUrl + '/address',
    CREATE: '',
    UPDATE: ':id',
    GET_ALL: '',
    DELETE: ':id',
  },
  SHIPPING: {
    CONTROLLER: ApiBaseUrl + '/shipping',
    CREATE: '',
    UPDATE: ':id',
    DELETE: ':id',
    GET_ALL: '',
    GET_ONE: ':id',
    GET_BY_SHIPPER_ID: 'get-by-shipper',
  },
  SHIPPING_FEE: {
    CONTROLLER: ApiBaseUrl + '/shipping-fee',
    CREATE: '',
    UPDATE: ':id',
    DELETE: ':id',
    GET_ALL: '',
    GET_ONE: ':id',
  },
  PRODUCT: {
    CONTROLLER: ApiBaseUrl + '/product',
    CREATE: '',
    UPDATE: ':id',
    DELETE: ':id',
    DELETE_MANY: 'delete-many',
    GET_ALL: '',
    GET_ONE: ':id',
  },
  CATEGORY: {
    CONTROLLER: ApiBaseUrl + '/category',
    CREATE: '',
    UPDATE: ':id',
    DELETE: ':id',
    GET_ALL: '',
    GET_ONE: ':id',
  },
  DISCOUNT: {
    CONTROLLER: ApiBaseUrl + '/discount',
    CREATE: '',
    UPDATE: ':id',
    DELETE: ':id',
    DELETE_MANY: 'delete-many',
    GET_ALL: '',
    GET_ONE: ':id',
  },
  CART: {
    CONTROLLER: ApiBaseUrl + '/cart',
    CREATE: '',
    UPDATE: ':id',
    GET: '',
    GET_ITEMS: 'items',
    GET_TOTAL_PRICE: 'total-price',
  },
  CART_ITEM: {
    CONTROLLER: ApiBaseUrl + '/cart-item',
    CREATE: '',
    UPDATE: ':id',
    DELETE: ':id',
    GET_BY_CART_ID: ':cartId',
  },
  UPLOAD: {
    CONTROLLER: ApiBaseUrl + '/upload',
    UPLOAD: '',
    DESTROY: 'destroy',
  },
  PRODUCT_IMAGE: {
    CONTROLLER: ApiBaseUrl + '/product-image',
    ADD: '',
    GET_PRODUCT_IMAGES: ':productId',
  },
  ORDER: {
    CONTROLLER: ApiBaseUrl + '/order',
    CREATE: '',
    GET_BY_MEMBER: 'get-by-member',
    GET_ALL: '',
    UPDATE: ':id',
    GET_ONE: ':orderId',
  },
};
