export enum OrderStatus {
  PROCESSING = 'PROCESSING',
  ASSIGNED = 'ASSIGNED',
  ACCEPTED = 'ACCEPTED',
  REFUSED = 'REFUSED',
  DELIVERING = 'DELIVERING',
  DELIVERED = 'DELIVERED',
  COMPLETED = 'COMPLETED',
  CANCELED = 'CANCELED',
  RETURNED = 'RETURNED',
}
